require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Lint/ConstantDefinitionInBlock:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false
