#!/bin/bash
#
# Script to get local dev server up and running

# Unique session name
session="my_dev_session"

cd ~/dev/flown.com/

# Create a new detached session
tmux new-session -d -s $session

# First window (0) -- vim
tmux send-keys -t $session "vim ." C-m


# Split window horizontally, 25% pane
tmux splitw -h -p 25 -t $session

tmux splitw -v -p 75 -t $session
tmux send-keys -t $session "docker compose up" C-m

# Split window vertically, 75% pane
tmux splitw -v -p 75 -t $session
tmux send-keys -t $session "npm run dev:32" C-m

# Split window vertically, 60% pane
tmux splitw -v -p 60 -t $session

# Attach to the session
tmux attach -t $session

# Script ends here
