require("core.plugin_config.mason")
require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.vim-test")

require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gitsigns")
require("core.plugin_config.supermaven")
require("core.plugin_config.colorizer")

require("core.plugin_config.null-ls")
require("core.plugin_config.which-key")
require("core.plugin_config.comments")
require("core.plugin_config.glow")
require("core.plugin_config.persisted")
require("core.plugin_config.avante")
